import { MenuItem, RestaurantTable } from "./types";

// Dish names and descriptions are based on real, publicly documented menu
// items for Texas Steak House (Rawalpindi). Prices were not publicly listed,
// so the figures below are indicative estimates for this demo — please
// confirm current prices with the restaurant directly.

export const menuItems: MenuItem[] = [
  {
    id: "s1",
    name: "Loaded Nachos",
    description:
      "Crisp tortilla chips piled with melted cheese, jalapeños, salsa, and sour cream.",
    price: 650,
    category: "Starters",
    isVeg: true,
    isPopular: true,
    image: "/images/pexels-himanuuu-36989884.jpg",
  },
  {
    id: "s2",
    name: "Garlic Bread",
    description: "Warm, buttery garlic bread — a Texas Steak House classic starter.",
    price: 350,
    category: "Starters",
    isVeg: true,
    isPopular: true,
    image: "/images/pexels-jack-baghel-2199968-20446381.jpg",
  },
  {
    id: "s3",
    name: "Harvest Salad",
    description: "Fresh greens, seasonal vegetables, and a light house dressing.",
    price: 550,
    category: "Starters",
    isVeg: true,
    image: "/images/pexels-visualstoriesbytugba-36425896.jpg",
  },
  {
    id: "m1",
    name: "Texas Fire Steak",
    description:
      "Our signature fire-grilled steak, fresh never frozen, finished with a smoky spice rub.",
    price: 2200,
    category: "Main Course",
    isVeg: false,
    isSpicy: true,
    isPopular: true,
    image: "/images/pexels-madknoxxdeluxe-37923406.jpg",
  },
  {
    id: "m2",
    name: "New York Strip",
    description: "A classic hand-cut strip steak, char-grilled to your liking.",
    price: 2600,
    category: "Main Course",
    isVeg: false,
    isPopular: true,
    image: "/images/pexels-lunajoie-19285833.jpg",
  },
  {
    id: "m3",
    name: "Twin Steak Combo",
    description: "Beef and chicken steak served together with grilled vegetables.",
    price: 2400,
    category: "Main Course",
    isVeg: false,
    isPopular: true,
    image: "/images/pexels-nosh-caterers-2148640437-30203310.jpg",
  },
  {
    id: "m4",
    name: "Chicken Fried Steak",
    description: "Breaded and pan-fried steak, smothered in creamy country gravy.",
    price: 1800,
    category: "Main Course",
    isVeg: false,
    image: "/images/pexels-erwin-quintana-917658-7963208.jpg",
  },
  {
    id: "m5",
    name: "Iron Skillet Steak",
    description: "Sizzling steak served straight from the skillet with sautéed onions.",
    price: 2100,
    category: "Main Course",
    isVeg: false,
    isSpicy: true,
    image: "/images/pexels-drmkhawarnazir-34193415.jpg",
  },
  {
    id: "m6",
    name: "Super Cheesy Chicken",
    description: "Grilled chicken breast smothered in a rich, gooey cheese sauce.",
    price: 1600,
    category: "Main Course",
    isVeg: false,
    image: "/images/pexels-dhiraj-jain-207743066-12737805.jpg",
  },
  {
    id: "b1",
    name: "Texas Chili Burger",
    description: "A hearty beef patty topped with spiced chili and melted cheese.",
    price: 950,
    category: "Burgers & Sandwiches",
    isVeg: false,
    isSpicy: true,
    isPopular: true,
    image: "/images/pexels-abdelilah-hibat-allah-1652683667-33408979.jpg",
  },
  {
    id: "b2",
    name: "Texas Chicken Burger",
    description: "Crispy chicken fillet burger with lettuce, tomato, and house sauce.",
    price: 850,
    category: "Burgers & Sandwiches",
    isVeg: false,
    image: "/images/pexels-shameel-mukkath-3421394-5639696.jpg",
  },
  {
    id: "b3",
    name: "Chicken Salad Sandwich",
    description: "Grilled chicken, fresh greens, and mayo on toasted bread.",
    price: 750,
    category: "Burgers & Sandwiches",
    isVeg: false,
    image: "/images/pexels-rajesh-tp-749235-1633525.jpg",
  },
  {
    id: "sd1",
    name: "Black & Blue Sirloin Salad",
    description: "Blackened sirloin strips over crisp greens with blue cheese crumble.",
    price: 1450,
    category: "Salads",
    isVeg: false,
    isPopular: true,
    image: "/images/pexels-kamrujjamanjewel-24866519.jpg",
  },
  {
    id: "d1",
    name: "New York Cheesecake",
    description: "Rich, creamy cheesecake with a buttery biscuit base.",
    price: 480,
    category: "Desserts",
    isVeg: true,
    isPopular: true,
    image: "/images/dessert5.jpg",
  },
  {
    id: "d2",
    name: "Chocolate Brownie",
    description: "Warm fudge brownie served with a scoop of vanilla ice cream.",
    price: 420,
    category: "Desserts",
    isVeg: true,
    image: "/images/dessert6.jpg",
  },
  {
    id: "v1",
    name: "Fresh Lime Soda",
    description: "Refreshing lime, soda, and a hint of mint.",
    price: 250,
    category: "Beverages",
    isVeg: true,
    image: "/images/fresh lime soda.jpg",
  },
  {
    id: "v2",
    name: "Iced Tea",
    description: "Chilled, lightly sweetened black tea.",
    price: 280,
    category: "Beverages",
    isVeg: true,
    isPopular: true,
    image: "/images/iced tea.jpg",
  },
];

export const menuCategories = Array.from(
  new Set(menuItems.map((item) => item.category))
);

export const tables: RestaurantTable[] = [
  { id: "t1", label: "T1", seats: 2, location: "Indoor" },
  { id: "t2", label: "T2", seats: 2, location: "Indoor" },
  { id: "t3", label: "T3", seats: 4, location: "Indoor" },
  { id: "t4", label: "T4", seats: 4, location: "Outdoor" },
  { id: "t5", label: "T5", seats: 6, location: "Outdoor" },
  { id: "t6", label: "T6", seats: 8, location: "Rooftop" },
  { id: "t7", label: "T7", seats: 10, location: "Private Room" },
];

export const DELIVERY_FEE = 150;
export const TAX_RATE = 0.05;
